// Autogenerated
// sdef FastScripts.app | sdp -fh --basename FastScripts

/*
 * FastScripts.h
 */

#import <AppKit/AppKit.h>
#import <ScriptingBridge/ScriptingBridge.h>


@class FastScriptsApplication, FastScriptsScriptLibrary, FastScriptsScriptItem, FastScriptsTopLevelScriptLibrary, FastScriptsKeyCombination, FastScriptsRichText, FastScriptsCharacter, FastScriptsParagraph, FastScriptsWord, FastScriptsAttributeRun, FastScriptsAttachment, FastScriptsWindow, FastScriptsMessageWindow;

// the location on the main screen at which the message will appear
typedef enum {
	FastScriptsScreenPositionTopLeft = 'tLft' /* Positioned near the top-left corner of the screen. */,
	FastScriptsScreenPositionTopCenter = 'tCtr' /* Positioned near the top-center of the screen. */,
	FastScriptsScreenPositionTopRight = 'tRte' /* Positioned near the top-right corner of the screen. */,
	FastScriptsScreenPositionCenter = 'cNtr' /* Positioned near the center of the screen. */,
	FastScriptsScreenPositionBottomLeft = 'bLft' /* Positioned near the bottom-left corner of the screen. */,
	FastScriptsScreenPositionBottomRight = 'bRte' /* Positioned near the bottom-right corner of the screen. */,
	FastScriptsScreenPositionBottomCenter = 'bCtr' /* Positioned near the bottom-center of the screen. */
} FastScriptsScreenPosition;

typedef enum {
	FastScriptsSaveOptionsYes = 'yes ' /* Save the file. */,
	FastScriptsSaveOptionsNo = 'no  ' /* Do not save the file. */,
	FastScriptsSaveOptionsAsk = 'ask ' /* Ask the user whether or not to save the file. */
} FastScriptsSaveOptions;

typedef enum {
	FastScriptsPrintingErrorHandlingStandard = 'lwst' /* Standard PostScript error handling */,
	FastScriptsPrintingErrorHandlingDetailed = 'lwdt' /* print a detailed report of PostScript errors */
} FastScriptsPrintingErrorHandling;



/*
 * FastScripts Suite
 */

// The application's top-level scripting object.
@interface FastScriptsApplication : SBApplication

- (SBElementArray *) windows;
- (SBElementArray *) topLevelScriptLibraries;
- (SBElementArray *) scriptItems;

@property (copy, readonly) NSString *name;  // The name of the application.
@property (readonly) BOOL frontmost;  // Is this the frontmost (active) application?
@property (copy, readonly) NSString *version;  // The version of the application.

- (FastScriptsMessageWindow *) displayMessage:(NSString *)x dismissingAfterDelay:(double)dismissingAfterDelay atScreenPosition:(FastScriptsScreenPosition)atScreenPosition;  // Display a self-dismissing message at a specificed location on the screen.
- (void) open:(id)x;  // Open a document.
- (void) print:(id)x withProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) quitSaving:(FastScriptsSaveOptions)saving;  // Quit the application.
- (BOOL) exists:(id)x;  // Verify if an object exists.

@end

// A hierarchical collection of script items.
@interface FastScriptsScriptLibrary : SBObject

- (SBElementArray *) scriptLibraries;
- (SBElementArray *) scriptItems;

@property (copy, readonly) NSString *name;  // The script library's name.
@property (copy, readonly) FastScriptsScriptLibrary *parentLibrary;  // The script library in which this item is hierarchically contained.  This property is undefined for top level script libraries.

- (void) closeSaving:(FastScriptsSaveOptions)saving savingIn:(NSURL *)savingIn;  // Close a document.
- (void) saveIn:(NSURL *)in_ as:(NSString *)as;  // Save a document.
- (void) printWithProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) delete;  // Delete an object.
- (SBObject *) duplicateTo:(SBObject *)to withProperties:(NSDictionary *)withProperties;  // Copy object(s) and put the copies at a new location.
- (SBObject *) moveTo:(SBObject *)to;  // Move object(s) to a new location.

@end

// A reference to a user-invokable script, application, or document.
@interface FastScriptsScriptItem : SBObject

@property (copy, readonly) NSString *name;  // The script item's name.
@property (copy, readonly) FastScriptsScriptLibrary *parentLibrary;  // The script library in which this item is hierarchically contained.
@property (copy, readonly) NSURL *scriptFile;  // If this script item was loaded from a file on disk, this is a reference to that file.
@property BOOL hasKeyboardShortcut;  // True if this script item is assigned a keyboard shortcut
@property (copy) FastScriptsKeyCombination *keyboardShortcut;  // The key combination assigned as the shortcut for this script, if any.

- (void) invoke;  // Invoke a script item in a manner identical to the user selecting the item by menu or keyboard shortcut. WARNING: Exercise caution when using this command from within a script executed by FastScripts as recursive cycle may occur.
- (void) closeSaving:(FastScriptsSaveOptions)saving savingIn:(NSURL *)savingIn;  // Close a document.
- (void) saveIn:(NSURL *)in_ as:(NSString *)as;  // Save a document.
- (void) printWithProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) delete;  // Delete an object.
- (SBObject *) duplicateTo:(SBObject *)to withProperties:(NSDictionary *)withProperties;  // Copy object(s) and put the copies at a new location.
- (SBObject *) moveTo:(SBObject *)to;  // Move object(s) to a new location.

@end

// a script library that is not contained by any other script library and which therefore possesses certain magical qualities
@interface FastScriptsTopLevelScriptLibrary : FastScriptsScriptLibrary


@end

// A description of a combination of characters, such as you might use for a keyboard shortcut.
@interface FastScriptsKeyCombination : SBObject

@property (copy, readonly) NSString *shortcutString;  // A unicode representation of the modifier keys and keyboard character that comprise this combination.

- (void) closeSaving:(FastScriptsSaveOptions)saving savingIn:(NSURL *)savingIn;  // Close a document.
- (void) saveIn:(NSURL *)in_ as:(NSString *)as;  // Save a document.
- (void) printWithProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) delete;  // Delete an object.
- (SBObject *) duplicateTo:(SBObject *)to withProperties:(NSDictionary *)withProperties;  // Copy object(s) and put the copies at a new location.
- (SBObject *) moveTo:(SBObject *)to;  // Move object(s) to a new location.

@end



/*
 * Text Suite
 */

// Rich (styled) text
@interface FastScriptsRichText : SBObject

- (SBElementArray *) characters;
- (SBElementArray *) paragraphs;
- (SBElementArray *) words;
- (SBElementArray *) attributeRuns;
- (SBElementArray *) attachments;

@property (copy) NSColor *color;  // The color of the first character.
@property (copy) NSString *font;  // The name of the font of the first character.
@property NSInteger size;  // The size in points of the first character.

- (void) closeSaving:(FastScriptsSaveOptions)saving savingIn:(NSURL *)savingIn;  // Close a document.
- (void) saveIn:(NSURL *)in_ as:(NSString *)as;  // Save a document.
- (void) printWithProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) delete;  // Delete an object.
- (SBObject *) duplicateTo:(SBObject *)to withProperties:(NSDictionary *)withProperties;  // Copy object(s) and put the copies at a new location.
- (SBObject *) moveTo:(SBObject *)to;  // Move object(s) to a new location.

@end

// This subdivides the text into characters.
@interface FastScriptsCharacter : SBObject

- (SBElementArray *) characters;
- (SBElementArray *) paragraphs;
- (SBElementArray *) words;
- (SBElementArray *) attributeRuns;
- (SBElementArray *) attachments;

@property (copy) NSColor *color;  // The color of the first character.
@property (copy) NSString *font;  // The name of the font of the first character.
@property NSInteger size;  // The size in points of the first character.

- (void) closeSaving:(FastScriptsSaveOptions)saving savingIn:(NSURL *)savingIn;  // Close a document.
- (void) saveIn:(NSURL *)in_ as:(NSString *)as;  // Save a document.
- (void) printWithProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) delete;  // Delete an object.
- (SBObject *) duplicateTo:(SBObject *)to withProperties:(NSDictionary *)withProperties;  // Copy object(s) and put the copies at a new location.
- (SBObject *) moveTo:(SBObject *)to;  // Move object(s) to a new location.

@end

// This subdivides the text into paragraphs.
@interface FastScriptsParagraph : SBObject

- (SBElementArray *) characters;
- (SBElementArray *) paragraphs;
- (SBElementArray *) words;
- (SBElementArray *) attributeRuns;
- (SBElementArray *) attachments;

@property (copy) NSColor *color;  // The color of the first character.
@property (copy) NSString *font;  // The name of the font of the first character.
@property NSInteger size;  // The size in points of the first character.

- (void) closeSaving:(FastScriptsSaveOptions)saving savingIn:(NSURL *)savingIn;  // Close a document.
- (void) saveIn:(NSURL *)in_ as:(NSString *)as;  // Save a document.
- (void) printWithProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) delete;  // Delete an object.
- (SBObject *) duplicateTo:(SBObject *)to withProperties:(NSDictionary *)withProperties;  // Copy object(s) and put the copies at a new location.
- (SBObject *) moveTo:(SBObject *)to;  // Move object(s) to a new location.

@end

// This subdivides the text into words.
@interface FastScriptsWord : SBObject

- (SBElementArray *) characters;
- (SBElementArray *) paragraphs;
- (SBElementArray *) words;
- (SBElementArray *) attributeRuns;
- (SBElementArray *) attachments;

@property (copy) NSColor *color;  // The color of the first character.
@property (copy) NSString *font;  // The name of the font of the first character.
@property NSInteger size;  // The size in points of the first character.

- (void) closeSaving:(FastScriptsSaveOptions)saving savingIn:(NSURL *)savingIn;  // Close a document.
- (void) saveIn:(NSURL *)in_ as:(NSString *)as;  // Save a document.
- (void) printWithProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) delete;  // Delete an object.
- (SBObject *) duplicateTo:(SBObject *)to withProperties:(NSDictionary *)withProperties;  // Copy object(s) and put the copies at a new location.
- (SBObject *) moveTo:(SBObject *)to;  // Move object(s) to a new location.

@end

// This subdivides the text into chunks that all have the same attributes.
@interface FastScriptsAttributeRun : SBObject

- (SBElementArray *) characters;
- (SBElementArray *) paragraphs;
- (SBElementArray *) words;
- (SBElementArray *) attributeRuns;
- (SBElementArray *) attachments;

@property (copy) NSColor *color;  // The color of the first character.
@property (copy) NSString *font;  // The name of the font of the first character.
@property NSInteger size;  // The size in points of the first character.

- (void) closeSaving:(FastScriptsSaveOptions)saving savingIn:(NSURL *)savingIn;  // Close a document.
- (void) saveIn:(NSURL *)in_ as:(NSString *)as;  // Save a document.
- (void) printWithProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) delete;  // Delete an object.
- (SBObject *) duplicateTo:(SBObject *)to withProperties:(NSDictionary *)withProperties;  // Copy object(s) and put the copies at a new location.
- (SBObject *) moveTo:(SBObject *)to;  // Move object(s) to a new location.

@end

// Represents an inline text attachment. This class is used mainly for make commands.
@interface FastScriptsAttachment : FastScriptsRichText

@property (copy) NSString *fileName;  // The path to the file for the attachment


@end



/*
 * Standard Suite
 */

// A window.
@interface FastScriptsWindow : SBObject

@property (copy, readonly) NSString *name;  // The full title of the window.
- (NSInteger) id;  // The unique identifier of the window.
@property NSInteger index;  // The index of the window, ordered front to back.
@property NSRect bounds;  // The bounding rectangle of the window.
@property (readonly) BOOL closeable;  // Whether the window has a close box.
@property (readonly) BOOL minimizable;  // Whether the window can be minimized.
@property BOOL minimized;  // Whether the window is currently minimized.
@property (readonly) BOOL resizable;  // Whether the window can be resized.
@property BOOL visible;  // Whether the window is currently visible.
@property (readonly) BOOL zoomable;  // Whether the window can be zoomed.
@property BOOL zoomed;  // Whether the window is currently zoomed.

- (void) closeSaving:(FastScriptsSaveOptions)saving savingIn:(NSURL *)savingIn;  // Close a document.
- (void) saveIn:(NSURL *)in_ as:(NSString *)as;  // Save a document.
- (void) printWithProperties:(NSDictionary *)withProperties printDialog:(BOOL)printDialog;  // Print a document.
- (void) delete;  // Delete an object.
- (SBObject *) duplicateTo:(SBObject *)to withProperties:(NSDictionary *)withProperties;  // Copy object(s) and put the copies at a new location.
- (SBObject *) moveTo:(SBObject *)to;  // Move object(s) to a new location.

@end



/*
 * FastScripts UI Suite
 */

// A self dismissing window suitable for unobtrusively displaying a message on the screen.
@interface FastScriptsMessageWindow : FastScriptsWindow

@property double autodismissTime;  // time in seconds before the window will auto-dismiss
@property FastScriptsScreenPosition screenPosition;  // the location on the screen at which the message should appear


@end
